### ISSUE TITLE
Codegen fails with asterisk in description string

### ISSUE THREAD

**Issue by groundlar** [drwpow/openapi-typescript#1025]
**Description**
Codegen fails with asterisk in description string

AFAICT this is supported [by the v2 spec](https://swagger.io/specification/v2/)

```
> openapi-typescript ./specs/fail.json -o ./src/fail.ts

✨ openapi-typescript 3.0.1
🤞 Loading spec from ./specs/fail.json…
SyntaxError: Property or signature expected. (12:17)
  10 |
  11 | export interface definitions {
> 12 |   /** See lib/*/README.md#time */
     |                 ^
  13 | "CivilDateProto": {
  14 | "year"?: number;
  15 | "month"?: number;
    at Ve (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/parser-typescript.js:1:15607)
    at vz (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/parser-typescript.js:280:5919)
    at Object.yz [as parse] (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/parser-typescript.js:280:6242)
    at Object.parse (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/index.js:7334:23)
    at coreFormat (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/index.js:8645:18)
    at formatWithCursor2 (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/index.js:8837:18)
    at /Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/index.js:37229:12
    at Object.format (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/prettier/index.js:37243:12)
    at swaggerToTS (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/openapi-typescript/dist-node/index.js:568:19)
    at main (/Users/skylarcook/src/hive-ts/packages/hive-types/node_modules/openapi-typescript/bin/cli.js:64:18)

```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `8.19.2`                      |
| Node.js              | `18.10.0`                      |
| OS + version         | `macOS 12.6,` |

**Reproduction**
Minimum repro:

```
{
  "swagger": "2.0",
  "info": {
    "title": "Faily McFailwhale",
    "version": "202301182126",
    "description": "failure is the mother of invention"
  },
  "tags": [
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
  },
  "definitions": {
    "CivilDateProto": {
      "type": "object",
      "properties": {
        "year": {
          "type": "integer",
          "format": "int64",
          "title": "Expects a value in range [1000, 2999]"
        },
        "month": {
          "type": "integer",
          "format": "int64",
          "title": "Expects a value in range [1, 12]"
        },
        "day": {
          "type": "integer",
          "format": "int64",
          "title": "Expects a value in range [1, 31]"
        }
      },
      "description": "See lib/*/README.md#time"
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "description": "Authentication token, prefixed by Bearer: Bearer <token>",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ]
}
```

**Expected result**

Obvious.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by mitchell-merry** [comment]
Swagger 2.0 is no longer supported afaik. It also seems that you're using an old version of openapi-typescript. Upgrade to v5 (last version with swagger 2.0 support) and your example seems to work.
