### ISSUE TITLE
openapi-fetch: ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by jacktator** [drwpow/openapi-typescript#1188]
**Description**

When using `open-fetch` to create a basic http client, it reports error.

```
application/node_modules/openapi-fetch/dist/index.cjs:58
  const defaultHeaders = new Headers({
                         ^

ReferenceError: Headers is not defined
    at createClient (application/node_modules/openapi-fetch/dist/index.cjs:58:26)
    at Array.<anonymous> (application/dist/apps/my-app/main.js:314:46)
    at __webpack_require__ (application/dist/apps/my-app/main.js:543:41)
    at Array.Object.defineProperty.value (application/dist/apps/my-app/main.js:292:22)
    at __webpack_require__ (application/dist/apps/my-app/main.js:543:41)
    at Array.Object.defineProperty.value (application/dist/apps/my-app/main.js:104:22)
    at __webpack_require__ (application/dist/apps/my-app/main.js:543:41)
    at Array.Object.defineProperty.value (application/dist/apps/my-app/main.js:67:33)
    at __webpack_require__ (application/dist/apps/my-app/main.js:543:41)
    at Array.<anonymous> (application/dist/apps/my-app/main.js:32:28)
```

**Reproduction**

In NodeJS environment

I've installed `openapi-fetch@5.0.0` and `openapi-typescript@6.2.8`. 
I've used `open-typescript` to generate schema from yaml. No issue here. 
When using `open-fetch` to create a basic http client, it reports error.
```
export const client = createClient<paths>({
  baseUrl: BASE_URL,
});
```
Does `open-fetch` support running in node environment?

**Expected result**

It should not report type error. 

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Are you perhaps running on [Node <= 16](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers#browser_compatibility)? It might help to upgrade to the latest version (20 is recommended).

**Comment by jacktator** [comment]
HI @drwpow , Node version v16.20.0.

**Comment by jacktator** [comment]
I've managed to workaround this issue by installing `node-fetch`, and provided global access to `fetch` by adding a polyfill. 
Docs: https://www.npmjs.com/package/node-fetch?activeTab=readme

It's probably a good idea to mention this somewhere in `openapi-fetch` docs too, in case someone also came across this. @drwpow what do u think?

**Comment by drwpow** [comment]
Yeah just adding minimum Node version to the docs seems like a good idea (18? with a note on 16)
