### ISSUE TITLE
Error with negative numbers in enums

### ISSUE THREAD

**Issue by fitztrev** [drwpow/openapi-typescript#1659]
**Description**

If an enum has a negative number, getting this error. Here is an [example of a spec with one of the values](https://github.com/lichess-org/api/blob/7bb9f06d941dc34f1d4633137b51ff15ff42d314/doc/specs/tags/swisstournaments/api-swiss-new-teamId.yaml#L93-L94)

```
✨ openapi-typescript 7.0.0-next.0
(node:604330) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/home/trev/code/openapi-typescript/node_modules/.pnpm/typescript@5.4.5/node_modules/typescript/lib/typescript.js:21094
      Debug.assert(text.charCodeAt(0) !== 45 /* minus */, "Negative numbers should be created in combination with createPrefixUnaryExpression");
            ^

Error: Debug Failure. False expression: Negative numbers should be created in combination with createPrefixUnaryExpression
    at Object.createNumericLiteral (/home/trev/code/openapi-typescript/node_modules/.pnpm/typescript@5.4.5/node_modules/typescript/lib/typescript.js:21094:13)
    at tsLiteral (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/lib/ts.js:177:60)
    at Array.map (<anonymous>)
    at transformSchemaObjectWithComposition (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/schema-object.js:48:44)
    at transformSchemaObject (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/schema-object.js:6:18)
    at transformSchemaObjectCore (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/schema-object.js:269:23)
    at transformSchemaObjectWithComposition (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/schema-object.js:96:28)
    at transformSchemaObject (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/schema-object.js:6:18)
    at transformMediaTypeObject (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/media-type-object.js:7:12)
    at transformRequestBodyObject (file:///home/trev/code/openapi-typescript/packages/openapi-typescript/dist/transform/request-body-object.js:15:15)

Node.js v21.7.3
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | main @ 08ff135b7be9872cfe61ce9c072183e1ab3430c6                      |
| Node.js              | `21.7.3`                      |
| OS + version         | `ubuntu 22.04` |

**Reproduction**

```bash
git clone https://github.com/lichess-org/api.git
cd api/doc
npm i openapi-typescript@next
npx openapi-typescript specs/lichess-api.yaml -o lichess.d.ts
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by fitztrev** [comment]
This change fixes it for me: https://github.com/drwpow/openapi-typescript/compare/main...fitztrev:openapi-typescript:negative-enums

But I'm not familiar with the codebase so probably not in a PR-ready state. I duplicated some code from this section to get it working: https://github.com/drwpow/openapi-typescript/blob/8f2d62f677afb0bba4cda966f52932a107ef331e/packages/openapi-typescript/src/lib/ts.ts#L238-L244
