### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by danerlt** [drwpow/openapi-typescript#291]
hello, wen I run command `npx @manifoldco/swagger-to-ts swagger_ac.yaml --output ac.ts` (swagger_ac.yam is my swagger open Api file), it tips:
```
npm ERR! Unexpected end of JSON input while parsing near '....0","@types/jest":"^2'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-07-29T02_37_01_355Z-debug.log
Install for [ '@manifoldco/swagger-to-ts@latest' ] failed with code 1
```
this is the log file contents, how can i resovle it ?:
````
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@manifoldco/swagger-to-ts@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm-cache\\_npx\\15112',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session fa778542bb7e8a5d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @manifoldco/swagger-to-ts@latest request to https://registry.npmjs.org/@manifoldco%2fswagger-to-ts failed, reason: connect ETIMEDOUT 104.16.21.35:443
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 133652ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/@manifoldco%2fswagger-to-ts failed, reason: connect ETIMEDOUT 104.16.21.35:443
11 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:310:20)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:426:9)
11 verbose stack     at TLSSocket.emit (events.js:310:20)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)
11 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
12 verbose cwd D:\work\monitor\acs_server\doc\v1
13 verbose Windows_NT 10.0.18363
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@manifoldco/swagger-to-ts@latest" "--global" "--prefix" "C:\\Users\\Administrator\\AppData\\Roaming\\npm-cache\\_npx\\15112" "--loglevel" "error" "--json"
15 verbose node v12.16.2
16 verbose npm  v6.14.4
17 error code ETIMEDOUT
18 error errno ETIMEDOUT
19 error network request to https://registry.npmjs.org/@manifoldco%2fswagger-to-ts failed, reason: connect ETIMEDOUT 104.16.21.35:443
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose exit [ 1, true ]
```

**Comment by drwpow** [comment]
Hello! I believe either this was an issue with npm, or it might have been an issue with the privacy issues on the project.

Please update your code to use `npx openapi-typescript` instead, and you shouldn’t see the issue. Thanks!
