### ISSUE TITLE
Error: --raw-schema requires --version flag

### ISSUE THREAD

**Issue by felix-hubert-eai** [drwpow/openapi-typescript#650]
I am running
`npx openapi-typescript http://localhost:8000/openapi.json --output src/types/generated/types.ts --raw-schema`

And this fails with error 
```
Error: --raw-schema requires --version flag
    at main (/Users/felix.hubert/Projects/eai-xai-caps/webapp/node_modules/openapi-typescript/bin/cli.js:116:11)
    at Object.<anonymous> (/Users/felix.hubert/Projects/eai-xai-caps/webapp/node_modules/openapi-typescript/bin/cli.js:158:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```

Is a value required with the `--raw-schema `parameter?

I'm on 4.0.0

**Comment by dlgombert** [comment]
You have to add another flag that is formatted like `--version 3`.  It confused me at first too, but I don't know why.  I guess just not used to having a flag need another flag.

**Comment by felix-hubert-eai** [comment]
And is the version the openapi json's version? or openapi-typescript version?
I tried both and I'm getting the same error

**Comment by drwpow** [comment]
The `--raw-schema` flag lets you load a partial schema. But you need to tell it what you want the final output in OpenAPI 2 (`--version 2`) or OpenAPI 3 (`--version 3`).

Should we just assume OpenAPI 3 now rather than throwing an error?

**Comment by felix-hubert-eai** [comment]
My schema is openapi 3.0.2, using `--version`, I get this
```
Loading spec from http://localhost:8000/openapi.json…
SyntaxError: Type expected. (8:14)
   6 |
   7 | export interface schemas {
>  8 |   "openapi": ;
```

**Comment by peniqliotuv** [comment]
I am also getting this issue as well. However, not passing in the `rawSchema` flag seems to generate the schema  correctly, regardless of OpenAPI 2.0 or 3.0p
