### ISSUE TITLE
Schema escape issues for $ref

### ISSUE THREAD

**Issue by liangskyli** [drwpow/openapi-typescript#915]
version: openapi-typescript@5.3.0
system: windws
node: v14.19.3

my openapi3 json file
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "bff to openapi3",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/getUser2": {
      "get": {
        "operationId": "UserController.getUser2.DjHhjSamaD",
        "tags": ["User"],
        "summary": "",
        "description": "UserController.getUser2",
        "parameters": [
          {
            "in": "query",
            "name": "param1",
            "description": "",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "query",
            "name": "param2",
            "description": "",
            "required": false,
            "schema": {
              "type": "object",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "$ref": "#/components/schemas/IUserWithId"
                }
              ]
            }
          },
          {
            "in": "query",
            "name": "param3",
            "description": "",
            "required": false,
            "schema": {
              "type": "object",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "$ref": "#/components/schemas/IUserWithName"
                }
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {}
              }
            },
            "description": "Successful response"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "IUserWithId": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/Partial<Pick<IUser,\"id\">>"
          },
          {
            "type": "string"
          }
        ]
      },
      "Partial<Pick<IUser,\"id\">>": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          }
        }
      },
      "IUserWithName": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "required": ["name"]
      },
      "IUser": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          }
        },
        "required": ["id"]
      }
    }
  }
}

```
I use this openapi3 json file, generate ts file error

error info:
```
(node:9836) UnhandledPromiseRejectionWarning: SyntaxError: Property or signature expected. (17:1)
  15 |   schemas: {
  16 |     "IUserWithId": (components["schemas"]["Partial<Pick<IUser,\"id\">>"]) | (string);
> 17 | "Partial<Pick<IUser,"id">>": {
     | ^
  18 | "id"?: number;
  19 |
  20 | };
    at qe (*****\node_modules\prettier\parser-typescript.js:1)
    at UU (*****\node_modules\prettier\parser-typescript.js:280:5918)
    at Object.zU [as parse] (*****\node_modules\prettier\parser-typescript.js:280:6241)
    at Object.parse (*****\node_modules\prettier\index.js:7361:23)
    at coreFormat (*****\node_modules\prettier\index.js:8672:18)
    at formatWithCursor2 (*****\node_modules\prettier\index.js:8864:18)
    at *****\node_modules\prettier\index.js:39174:12
    at Proxy.format (*****\node_modules\prettier\index.js:39188:12)
    at openapiTS (*****\node_modules\openapi-typescript\src\index.ts:128:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

```
in line 17, "Partial<Pick<IUser,"id">>" ------error in this position, should generate to  "Partial<Pick<IUser,\"id\">>"
```

**Comment by mitchell-merry** [comment]
Minimal repro:
```yaml
openapi: 3.0.0
info:
  title: title
  version: 0.0.0
paths: {}
components:
  schemas:
    someschema:
      $ref: '#/components/schemas/"'
    '"':
      type: string
```

generates to:
```ts
export interface components {
  schemas: {
    someschema: components["schemas"]["\\""];
    "\"": string;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
```
