### ISSUE TITLE
Cannot read properties of undefined (reading 'schema')

### ISSUE THREAD

**Issue by bachu-shannon** [drwpow/openapi-typescript#975]
**Description**

_A brief description of the bug._

```
✨ openapi-typescript 6.0.1
file:///C:/Users/ba4yr/AppData/Local/npm-cache/_npx/21d31b7563e6adbc/node_modules/openapi-typescript/dist/load.js:141
    walk(options.schemas[schemaID].schema, (rawNode, nodePath) => {
                                   ^

TypeError: Cannot read properties of undefined (reading 'schema')
m-cache/_npx/21d31b7563e6adbc/node_modules/openapi-typescript/bin/cli.js:156:5)
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| openapi-typescript | v6.0.1                      |
| Node.js              | v16.17.0                      |
| OS + version         | ` Windows 10.` |

**Reproduction**

npx openapi-typescript {LINK} --output {PATH}

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This sounds like a bug but I’m not able to reproduce it without the schema. Could you provide either the schema or a small example reproducing the bug?

**Comment by dolegi** [comment]
I have the same issue. v5.4.1 works. But v6.0.1 causes this error. Can't share the schema public unfortunately, just wanted to add it another data point where it's happened.

<html>
<body>


Name | Version
-- | --
openapi-typescript | v6.0.1
Node.js | v16.17.1
OS + version | Windows 10.


</body>
</html>

**Comment by wolfy1339** [comment]
I have this issue as well. I'm compiling the GitHub Next schema

See https://github.com/octokit/octokit-next.js/issues/101#issue-1442623463

**Comment by drwpow** [comment]
@wolfy1339 thank you! I will add Octokit to the test suite. We were testing the GitHub REST API but not Octokit. Will get this fixed later today.

**Comment by drwpow** [comment]
Fixed a known occurrence of this issue in the Octokit schema. If this occurs for anyone again, please share a reproducible example and we can get it fixed! 🙏

**Comment by fehnomenal** [comment]
Nice, that this got fixed so fast. But sadly I get the same error with this schema: https://rmi-services.tecalliance.net/swagger/docs/4_2_22290_1241

```
> pnpm openapi-typescript https://rmi-services.tecalliance.net/swagger/docs/4_2_22290_1241 --output ./src/tec-rmi/schema.ts
✨ openapi-typescript 6.0.2
file:///.../node_modules/.pnpm/openapi-typescript@6.0.2/node_modules/openapi-typescript/dist/load.js:140
    const currentSchema = options.schemas[schemaID].schema;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'schema')
    at load (file:///.../node_modules/.pnpm/openapi-typescript@6.0.2/node_modules/openapi-typescript/dist/load.js:140:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async openapiTS (file:///.../node_modules/.pnpm/openapi-typescript@6.0.2/node_modules/openapi-typescript/dist/index.js:37:5)
    at async generateSchema (file:///.../node_modules/.pnpm/openapi-typescript@6.0.2/node_modules/openapi-typescript/bin/cli.js:89:18)
    at async main (file:///.../node_modules/.pnpm/openapi-typescript@6.0.2/node_modules/openapi-typescript/bin/cli.js:156:5)

Node.js v18.9.0
Exception: pnpm exited with 1
```
